services:
  tejas-postgres:
    image: postgres:15-alpine
    container_name: tejas-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: tejas_grid_db
      POSTGRES_USER: tejas_admin
      POSTGRES_PASSWORD: tejas_secure_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tejas_admin -d tejas_grid_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  tejas-influxdb:
    image: influxdb:2.7-alpine
    container_name: tejas-influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: tejas_admin_password_123
      DOCKER_INFLUXDB_INIT_ORG: tejas_grid_org
      DOCKER_INFLUXDB_INIT_BUCKET: campus_telemetry
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: tejas_super_secret_influx_token_2026
    volumes:
      - influxdb_data:/var/lib/influxdb2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/health"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    name: tejas_postgres_data
  influxdb_data:
    name: tejas_influxdb_data
