import React, { useEffect, useState } from 'react';
import { getExecutiveMetrics } from '../api/api';
import KpiCard from '../components/KpiCard';
import { Leaf, IndianRupee, Zap, Users, Download, CheckCircle } from 'lucide-react';

export default function ExecutiveDashboard() {
  const [metrics, setMetrics] = useState(null);
  const [downloaded, setDownloaded] = useState(false);

  useEffect(() => {
    getExecutiveMetrics().then((res) => setMetrics(res.data)).catch(console.error);
  }, []);

  const handleDownloadReport = () => {
    const reportContent = `==========================================================
TEJAS GRID — EXECUTIVE ESG & CARBON OFFSET REPORT
Campus Virtual Power Plant Autonomous Orchestration
Date: ${new Date().toLocaleDateString()}
==========================================================

1. FINANCIAL & ROI METRICS:
   - Total Peak Tariff Cost Avoided: ₹${metrics?.total_cost_saved_inr?.toLocaleString() || 0}
   - Tariff Rate Applied: ₹12.50 per kWh avoided

2. SUSTAINABILITY & EMISSIONS:
   - Scope 2 Carbon Emissions Avoided: ${metrics?.total_carbon_avoided_kg?.toLocaleString() || 0} kg CO2
   - Clean Energy Shifted to Renewables: ${metrics?.total_energy_saved_kwh?.toLocaleString() || 0} kWh
   - Participating Residential Blocks: ${metrics?.participating_hostels || 3} Hostels

3. COMPLIANCE & SAFETY ASSURANCE:
   - 30% Battery Critical Lab Reserve: ENFORCED & VERIFIED
   - Research Server Outage Protection: 100% Guaranteed
   - Behavioral Demand-Response Engagement: Twilio WhatsApp Active

Generated by TEJAS GRID Autonomous Energy Management System.
==========================================================`;

    const blob = new Blob([reportContent], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `TEJAS_GRID_ESG_Report_${new Date().toISOString().split('T')[0]}.txt`;
    link.click();
    URL.revokeObjectURL(url);

    setDownloaded(true);
    setTimeout(() => setDownloaded(false), 5000);
  };

  return (
    <div className="max-w-7xl mx-auto space-y-8 pb-24">
      <div>
        <h1 className="text-3xl font-extrabold text-slate-900 tracking-tight">Executive Analytics</h1>
        <p className="text-slate-500 text-sm">Automated Scope 2 Carbon & Peak Tariff ROI Reporting</p>
      </div>

      {metrics ? (
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
          <KpiCard
            title="Total Cost Saved"
            value={`₹${(metrics.total_cost_saved_inr || 0).toLocaleString()}`}
            unit="INR"
            icon={IndianRupee}
          />
          <KpiCard
            title="Carbon Avoided"
            value={(metrics.total_carbon_avoided_kg || 0).toLocaleString()}
            unit="kg CO₂"
            icon={Leaf}
          />
          <KpiCard
            title="Peak Energy Shifted"
            value={(metrics.total_energy_saved_kwh || 0).toLocaleString()}
            unit="kWh"
            icon={Zap}
          />
          <KpiCard
            title="Participating Hostels"
            value={metrics.participating_hostels || 3}
            unit="Blocks"
            icon={Users}
          />
        </div>
      ) : (
        <div className="bg-white p-6 rounded-2xl border border-slate-200 text-center text-slate-400 animate-pulse">
          Loading Executive ESG analytics...
        </div>
      )}

      <div className="bg-white rounded-2xl shadow-sm border border-slate-200 p-8 text-center min-h-[300px] flex items-center justify-center">
        <div className="max-w-lg space-y-4">
          <div className="w-16 h-16 bg-emerald-50 text-emerald-600 rounded-2xl flex items-center justify-center mx-auto shadow-inner">
            <Leaf size={32} />
          </div>
          <h2 className="text-2xl font-black text-slate-900 tracking-tight">
            Scope 2 Carbon Offset Report Generated
          </h2>
          <p className="text-slate-500 text-sm leading-relaxed">
            The automated VPP has successfully shifted {metrics?.total_energy_saved_kwh || 0} kWh from peak grid reliance to renewable assets.
          </p>

          <button
            onClick={handleDownloadReport}
            className="bg-slate-950 hover:bg-slate-800 text-white px-6 py-3 rounded-xl font-bold text-sm shadow-xl flex items-center gap-2.5 mx-auto transition-all transform active:scale-95 cursor-pointer"
          >
            {downloaded ? (
              <>
                <CheckCircle size={18} className="text-emerald-400" /> Report Downloaded!
              </>
            ) : (
              <>
                <Download size={18} /> Download Official ESG Report (.txt)
              </>
            )}
          </button>
        </div>
      </div>
    </div>
  );
}
