import React, { useEffect, useState } from 'react';
import { getExecutiveMetrics } from '../api/api';
import KpiCard from '../components/KpiCard';
import ExecutiveCalculationModal from '../components/ExecutiveCalculationModal';
import { Leaf, IndianRupee, Zap, Users, Download, CheckCircle, Calculator, ShieldCheck } from 'lucide-react';

export default function ExecutiveDashboard() {
  const [metrics, setMetrics] = useState(null);
  const [downloaded, setDownloaded] = useState(false);
  const [showFormulaModal, setShowFormulaModal] = useState(false);

  useEffect(() => {
    getExecutiveMetrics().then((res) => setMetrics(res.data)).catch(console.error);
  }, []);

  const handleDownloadReport = () => {
    const reportContent = `==========================================================
TEJAS GRID — EXECUTIVE ESG & CARBON OFFSET REPORT
Campus Virtual Power Plant Autonomous Orchestration
Date: ${new Date().toLocaleDateString()}
==========================================================

1. FINANCIAL & ROI METRICS:
   - Total Peak Tariff Cost Avoided: ₹${metrics?.total_cost_saved_inr?.toLocaleString() || 0}
   - Tariff Rate Applied: ₹12.50 per kWh avoided (India Commercial ToD Peak Rate)

2. SUSTAINABILITY & EMISSIONS:
   - Scope 2 Carbon Emissions Avoided: ${metrics?.total_carbon_avoided_kg?.toLocaleString() || 0} kg CO2
   - Emission Factor Applied: 0.82 kg CO2 / kWh (CEA Baseline Database v19)
   - Clean Energy Shifted to Renewables: ${metrics?.total_energy_saved_kwh?.toLocaleString() || 0} kWh
   - Equivalent Mature Trees Planted: ${Math.round((metrics?.total_carbon_avoided_kg || 0) / 21.77)} Trees
   - Participating Residential Blocks: ${metrics?.participating_hostels || 3} Hostels

3. COMPLIANCE & SAFETY ASSURANCE:
   - 30% Battery Critical Lab Reserve: ENFORCED & VERIFIED (240 kWh Floor)
   - Research Server Outage Protection: 100% Guaranteed
   - Behavioral Demand-Response Engagement: WhatsApp Direct Automated Alerts

Generated by TEJAS GRID Autonomous Energy Management System.
==========================================================`;

    const blob = new Blob([reportContent], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `TEJAS_GRID_ESG_Report_${new Date().toISOString().split('T')[0]}.txt`;
    link.click();
    URL.revokeObjectURL(url);

    setDownloaded(true);
    setTimeout(() => setDownloaded(false), 5000);
  };

  return (
    <div className="max-w-7xl mx-auto space-y-8 pb-24 font-sans">
      <div className="flex flex-wrap justify-between items-center gap-4">
        <div>
          <h1 className="text-3xl font-extrabold text-slate-900 dark:text-white tracking-tight">Executive Analytics</h1>
          <p className="text-slate-500 dark:text-slate-400 text-sm">Automated Scope 2 Carbon & Peak Tariff ROI Reporting</p>
        </div>

        {/* CALCULATION FORMULA BUTTON */}
        <button
          onClick={() => setShowFormulaModal(true)}
          className="px-4 py-2 rounded-xl bg-amber-500/15 hover:bg-amber-500/25 text-amber-700 dark:text-amber-400 border border-amber-500/40 text-xs font-bold flex items-center gap-2 transition cursor-pointer"
        >
          <Calculator size={15} />
          <span>📐 How Metrics Are Calculated</span>
        </button>
      </div>

      {metrics ? (
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
          <KpiCard
            title="Total Cost Saved"
            value={`₹${(metrics.total_cost_saved_inr || 0).toLocaleString()}`}
            unit="INR"
            icon={IndianRupee}
          />
          <KpiCard
            title="Carbon Avoided"
            value={(metrics.total_carbon_avoided_kg || 0).toLocaleString()}
            unit="kg CO₂"
            icon={Leaf}
          />
          <KpiCard
            title="Peak Energy Shifted"
            value={(metrics.total_energy_saved_kwh || 0).toLocaleString()}
            unit="kWh"
            icon={Zap}
          />
          <KpiCard
            title="Participating Hostels"
            value={metrics.participating_hostels || 3}
            unit="Blocks"
            icon={Users}
          />
        </div>
      ) : (
        <div className="bg-white dark:bg-slate-900 p-6 rounded-2xl border border-slate-200 dark:border-slate-800 text-center text-slate-400 animate-pulse">
          Loading Executive ESG analytics...
        </div>
      )}

      <div className="bg-white dark:bg-slate-900 rounded-3xl shadow-sm border border-slate-200 dark:border-slate-800 p-8 text-center min-h-[300px] flex items-center justify-center">
        <div className="max-w-lg space-y-4">
          <div className="w-16 h-16 bg-emerald-50 dark:bg-emerald-950/50 text-emerald-600 dark:text-emerald-400 rounded-2xl flex items-center justify-center mx-auto shadow-inner border border-emerald-500/20">
            <Leaf size={32} />
          </div>
          <h2 className="text-2xl font-black text-slate-900 dark:text-white tracking-tight">
            Scope 2 Carbon Offset Report Generated
          </h2>
          <p className="text-slate-500 dark:text-slate-400 text-sm leading-relaxed">
            The automated VPP has successfully shifted {metrics?.total_energy_saved_kwh || 0} kWh from peak grid reliance to renewable assets, avoiding ₹{metrics?.total_cost_saved_inr?.toLocaleString() || 0} in commercial utility tariffs.
          </p>

          <div className="flex flex-wrap items-center justify-center gap-3 pt-2">
            <button
              onClick={handleDownloadReport}
              className="bg-slate-950 dark:bg-emerald-600 dark:hover:bg-emerald-500 hover:bg-slate-800 text-white px-6 py-3 rounded-xl font-bold text-sm shadow-xl flex items-center gap-2.5 transition-all transform active:scale-95 cursor-pointer"
            >
              {downloaded ? (
                <>
                  <CheckCircle size={18} className="text-emerald-400 dark:text-white" /> Report Downloaded!
                </>
              ) : (
                <>
                  <Download size={18} /> Download Official ESG Report (.txt)
                </>
              )}
            </button>

            <button
              onClick={() => setShowFormulaModal(true)}
              className="px-5 py-3 rounded-xl bg-slate-100 dark:bg-slate-800 hover:bg-slate-200 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-200 border border-slate-200 dark:border-slate-700 font-bold text-sm flex items-center gap-2 transition cursor-pointer"
            >
              <Calculator size={16} />
              <span>View Accounting Formulas</span>
            </button>
          </div>
        </div>
      </div>

      {/* EXECUTIVE CALCULATION MODAL */}
      <ExecutiveCalculationModal
        isOpen={showFormulaModal}
        onClose={() => setShowFormulaModal(false)}
      />
    </div>
  );
}
